# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('alpha2', models.CharField(max_length=2, unique=True)),
                ('alpha3', models.CharField(max_length=3, unique=True)),
                ('languages', models.ManyToManyField(to='core.Language')),
                ('neighbors', models.ManyToManyField(related_name='_country_neighbors_+', to='core.Country')),
            ],
        ),
    ]
